In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import joblib
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix, hstack
from langdetect import detect, DetectorFactory
import seaborn as sns

In [2]:
bundle = joblib.load("multilabel_project_bundle.pkl")

model = bundle["model"]
thresholds = bundle["thresholds"]
label_cols = bundle["label_cols"]

print("✅ Model loaded")
print("Labels:", label_cols)
print("Thresholds:", thresholds)

✅ Model loaded
Labels: ['Attitude_Towards_Students', 'Campus_conditions', 'Corruption', 'Academic_Process_Management', 'Education_Quality']
Thresholds: [0.51, 0.525, 0.5, 0.47, 0.5]

In [3]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
)

print("✅ MPNet loaded")

✅ MPNet loaded

In [5]:
full_df = pd.read_csv("full_df.csv", sep = ',')
full_df .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6254 entries, 0 to 6253
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   University Name              6254 non-null   object
 1   Review Text                  6254 non-null   object
 2   Cleaned_Text                 2279 non-null   object
 3   Language                     6254 non-null   object
 4   Year                         6254 non-null   int64
 5   Sentiment_Category           6254 non-null   object
 6   Attitude_Towards_Students    615 non-null    float64
 7   Campus_conditions            614 non-null    float64
 8   Corruption                   614 non-null    float64
 9   Academic_Process_Management  614 non-null    float64
 10  Education_Quality            614 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 537.6+ KB

In [6]:
negative_unlabeled = full_df[
    full_df["Sentiment_Category"] == "negative"
].copy()

print(negative_unlabeled.shape)

(1676, 11)

In [12]:
texts = negative_unlabeled["Cleaned_Text"].fillna("").tolist()

embeddings = embedding_model.encode(
    texts,
    batch_size=32,
    show_progress_bar=True
)

Batches:   0%|          | 0/53 [00:00<?, ?it/s]

In [13]:
probs = model.predict_proba(embeddings)
preds = (
    probs >= np.array(thresholds)
).astype(int)
for i, label in enumerate(label_cols):

    negative_unlabeled[f"{label}_prob"] = probs[:, i]
for i, label in enumerate(label_cols):

    negative_unlabeled[f"{label}_pred"] = preds[:, i]
negative_unlabeled["Predicted_Issues"] = [
    ", ".join(
        [
            label_cols[j]
            for j in range(len(label_cols))
            if row[j] == 1
        ]
    )
    for row in preds
]

negative_unlabeled.tail()

,University Name,Review Text,Cleaned_Text,Language,Year,Sentiment_Category,Attitude_Towards_Students,Campus_conditions,Corruption,Academic_Process_Management,...,Campus_conditions_prob,Corruption_prob,Academic_Process_Management_prob,Education_Quality_prob,Attitude_Towards_Students_pred,Campus_conditions_pred,Corruption_pred,Academic_Process_Management_pred,Education_Quality_pred,Predicted_Issues
2274,University_19,"Если вы надеетесь чему то научиться, получить ...","Если вы надеетесь чему то научиться, получить ...",ru,2016,negative,NaN,NaN,NaN,NaN,...,0.096939,0.448327,0.369244,0.887351,0,0,0,0,1,Education_Quality
2275,University_19,"каждый раз при открытии word документа, или да...","каждый раз при открытии word документа, или да...",ru,2016,negative,NaN,NaN,NaN,NaN,...,0.460610,0.292557,0.922218,0.451797,0,0,0,1,0,Academic_Process_Management
2276,University_19,"They will just take your money that's all, \nY...","They will just take your money that' s all, Yo...",en,2016,negative,NaN,NaN,NaN,NaN,...,0.043528,0.903791,0.211025,0.701291,0,0,1,0,1,"Corruption, Education_Quality"
2277,University_19,Не розумію чому рейтинг цього ВНЗ такий високи...,Не розумію чому рейтинг цього ВНЗ такий високи...,uk,2016,negative,NaN,NaN,NaN,NaN,...,0.356146,0.368243,0.404405,0.422597,0,0,0,0,0,
2278,University_1,"учусь 4й год,с первого курса обещают дать акре...","учусь 4й год, с первого курса обещают дать акр...",ru,2010,negative,NaN,NaN,NaN,NaN,...,0.195268,0.397758,0.695162,0.691268,0,0,0,1,1,"Academic_Process_Management, Education_Quality"

In [14]:
# # Update full dataset with processed negative unlabeled records
full_df.loc[
    negative_unlabeled.index,
    negative_unlabeled.columns
] = negative_unlabeled

In [22]:
full_df[full_df["Sentiment_Category"] == 'negative'].tail()

,University Name,Review Text,Cleaned_Text,Language,Year,Sentiment_Category,Attitude_Towards_Students,Campus_conditions,Corruption,Academic_Process_Management,...,Campus_conditions_prob,Corruption_prob,Academic_Process_Management_prob,Education_Quality_prob,Attitude_Towards_Students_pred,Campus_conditions_pred,Corruption_pred,Academic_Process_Management_pred,Education_Quality_pred,Predicted_Issues
2274,University_19,"Если вы надеетесь чему то научиться, получить ...","Если вы надеетесь чему то научиться, получить ...",ru,2016,negative,NaN,NaN,NaN,NaN,...,0.096939,0.448327,0.369244,0.887351,0.0,0.0,0.0,0.0,1.0,Education_Quality
2275,University_19,"каждый раз при открытии word документа, или да...","каждый раз при открытии word документа, или да...",ru,2016,negative,NaN,NaN,NaN,NaN,...,0.460610,0.292557,0.922218,0.451797,0.0,0.0,0.0,1.0,0.0,Academic_Process_Management
2276,University_19,"They will just take your money that's all, \nY...","They will just take your money that' s all, Yo...",en,2016,negative,NaN,NaN,NaN,NaN,...,0.043528,0.903791,0.211025,0.701291,0.0,0.0,1.0,0.0,1.0,"Corruption, Education_Quality"
2277,University_19,Не розумію чому рейтинг цього ВНЗ такий високи...,Не розумію чому рейтинг цього ВНЗ такий високи...,uk,2016,negative,NaN,NaN,NaN,NaN,...,0.356146,0.368243,0.404405,0.422597,0.0,0.0,0.0,0.0,0.0,
2278,University_1,"учусь 4й год,с первого курса обещают дать акре...","учусь 4й год, с первого курса обещают дать акр...",ru,2010,negative,NaN,NaN,NaN,NaN,...,0.195268,0.397758,0.695162,0.691268,0.0,0.0,0.0,1.0,1.0,"Academic_Process_Management, Education_Quality"

In [24]:
# frequency of problems
label_cols_pred = [
    "Attitude_Towards_Students_pred",
    "Campus_conditions_pred",
    "Corruption_pred",
    "Academic_Process_Management_pred",
    "Education_Quality_pred"
]

issue_counts = full_df[label_cols_pred].sum().sort_values(ascending=False)

issue_counts

Education_Quality_pred              819.0
Academic_Process_Management_pred    658.0
Attitude_Towards_Students_pred      572.0
Corruption_pred                     570.0
Campus_conditions_pred              317.0
dtype: float64

In [25]:
full_df.to_excel("student_feedback.xlsx")

### Qualitative Analysis of Predictions

**1. Highest-confidence predictions**

The examples below correspond to the highest-confidence predictions produced by the model. They are intended to illustrate the semantic patterns learned by the classifier rather than to represent its overall performance. Model quality is evaluated separately using the validation and test metrics reported above.

In [69]:
for label in label_cols:

    print(f"\n{'='*100}")
    print(f"🏷️ {label}")
    print(f"{'='*100}")

    top_reviews = negative_unlabeled.sort_values(
        f"{label}_prob",
        ascending=False
    ).head(5)

    for i, (_, row) in enumerate(top_reviews.iterrows(), 1):

        print(f"\n🔹 Example #{i}")
        print(f"📈 Probability: {row[f'{label}_prob']:.3f}")
        print(f"📝 {row['Review Text']}")

====================================================================================================
🏷️ Attitude_Towards_Students
====================================================================================================

🔹 Example #1
📈 Probability: 0.969
📝 ненавиджу цей університет.викладачі постійно повторюють,що ми,студенти,дорослі люди,ми їх колеги і т.д.,а самі ставляться як до бидлоти до "колег"!У розмові з викладачем повинен підтакувати,погоджуватись у всьому,завжди (незалежно від ситуації) у відносинах викладач-студент,студент - ніхто і ніщо.Коли ти виправдовуєшся,відстоюєш свою точку зору...викладач каже:"Не хаміть!"(!)...про що може йти річ?..Після такого навіть привітатись боїшся...не те,щоб шось запитати чи сказати..

🔹 Example #2
📈 Probability: 0.961
📝 Как бывшей студентке данного ВУЗа очень неприятно осознавать, что в общежитиях управляющий персонал каким был таким и остался- грубым "хамлом", позволяющим себе обзывать, третировать студентов и вымагать деньги!

🔹 Example #3
📈 Probability: 0.959
📝 Не раджу вступати до цього університету! Ставлення до студентів просто жахливе, грубе, нахальне. Адекватних людей одиниці, всі інші ставляться без поваги та неадекватно відносяться, до того ж деякі розмовляють "рузкім язиком". Жах

🔹 Example #4
📈 Probability: 0.955
📝 Плохие впечатления:Друг первокурсник рассказывал что оценки ставятся не обьективно, одногрупники обычно слишком самовлюбленные, преподы заносчивые

🔹 Example #5
📈 Probability: 0.953
📝 Преподаватели не умеют нормально общаться со студентами - отношение как к пустому месту!

====================================================================================================
🏷️ Campus_conditions
====================================================================================================

🔹 Example #1
📈 Probability: 0.994
📝 Дуже холодно в аудиторіях. Всі хворіють. В КПІ залишите своє здоров'я

🔹 Example #2
📈 Probability: 0.994
📝 Дуже холодно в аудиторіях. Не опалюють як слід, діти хворіють

🔹 Example #3
📈 Probability: 0.994
📝 Зайшли в 11 гуртожиток .Це жах.Цвіль та грибок в кімнатах.Туалети гірше ніж на зоні.Речі немає де сушити.Один зламаний шкафчик на 4 студента.Підлоги немає.Якісь умови для скотини.

🔹 Example #4
📈 Probability: 0.992
📝 Общага - это мусор, где ночью у тебя на стенке ползают под десяток тараканов, соседи которые бесят, включают свет в час ночи и орут по телефону, не моют посуду. Душ это сплошной грибок, обшарпанные потолки, ржавые краны, грязные полы. Возле лифта мусоропровод возле которого можно задохнуться пока ждёшь лифт, который не едет вниз и только на парные этажи. Университет холодный, преподаватели хамы, каждая пара в другом корпусе, пара длиться 1:30 мин. и перемена 15 минут за которые не успеваешь перекусить, так как ты бегаешь с 8 корпуса вo 2 занимает все твое время. Хотите испортить себе нервную систему и потратить время зря? Значит НАУ для вас!

🔹 Example #5
📈 Probability: 0.990
📝 Це бурса. Смердючими туалетами, совковими коридорами і аудиторіями.

====================================================================================================
🏷️ Corruption
====================================================================================================

🔹 Example #1
📈 Probability: 0.999
📝 Корупція, корупція, корупція.

🔹 Example #2
📈 Probability: 0.993
📝 Ужасный университет, коррупция и взятки с первого дня!

🔹 Example #3
📈 Probability: 0.992
📝 Це жах корупція на кожному кроці

🔹 Example #4
📈 Probability: 0.990
📝 Для тех, кто пишет, что проучились без взяток, поэтому коррупции нет, нужно понимать две стороны медали. Коррупции нет, если не продаются места в вузе, экзамены, сессии, и даже дипломы - тогда коррупции нет, а если часть преподавателей готова поставить оценку за взятку, если по договоренности с низкими балами вы можете получить даже бюджетное место, а это означает, что какой-то ребенок, сдавший на отлично экзамены не сможет поступить на это место - тогда коррупция есть в данном вузе, просто вы обошли ее стороной, но это не исключает наличия таковой. Нельзя винить одну сторону, студенты могут давать деньги сколько угодно, но если преподаватель принципиально не согласен на это - кто его заставит? если места не будут продаваться, вы можете свои деньги давать кому угодно, но поступить за них не сможете.. все начинается с предложения, а на любое предложение рождается спрос. А есть и те, кто намеками вымогают, валят и заставляют студентов писать свои диссертации за дополнительные баллы.

🔹 Example #5
📈 Probability: 0.988
📝 Плохой университет, где очень много взяток!

====================================================================================================
🏷️ Academic_Process_Management
====================================================================================================

🔹 Example #1
📈 Probability: 0.966
📝 "Зарахування до НУБіП України у 2019 році відбуватиметься на підставі конкурсного відбору" це відповідь на одне з запитань на сайті універа, а на справді конкурсна комісія каже вже вести документи тим хто знаходиться на самому дні рейтингового списку хоча до його опублікування ще 3 дні. Виходить ті що чекають на бюджет за двієчниками можуть не встигнути і на контракт.

🔹 Example #2
📈 Probability: 0.956
📝 Сейчас учусь в этом универе на заочке и меня очень настораживает ситуация с моей дипломной работой.
Дело в том, что защита дипломной работы уже через месяц, а его всё никак не могут проверить. Сменилось уже 2 руководителя! Второй руководитель морочил мне голову 4 месяца, ссылаясь на то, что у него не было времени проверить мой диплом. Но, прошло 3 месяца и он его всё же проверил и внёс правки и через месяц уволился, не проверив исправленный вариант. Потом был назначен новый "третий руководитель".
Занимается он тем же, что и второй, уже 3-ю неделю.
А диплом нужно сдать за 15 дней до защиты - осталось чуть больше 2 недель до полной сдачи со всеми дополнениями к диплому, а я всё остаюсь в неведении!
Когда я заканчивал бакалаврат (это было в другом универе), мой руководитель (да и остальные на кафедре) сразу проверяли работу и не допускали таких ситуаций со студентами, всегда шли на встречу.
А в КНТЕУ такое отношение видимо "нонсенс"!
Хоть бы всё благополучно закончилось...

🔹 Example #3
📈 Probability: 0.953
📝 Буквально на прошлой неделе узнала, что с 1 января 2004 года, учеба в вузе не идёт в страховой стаж, даже если ты на бюджете. Почему это не сообщалось студентам? Или мы должны будем это узнавать при оформлении пенсии, что 6 лет в трубу? А вы знаете, что для выхода на пенсию надо будет 35 лет стажа? И 6 лет это очень критично. Вам кроме своих мест и грантов на всё плевать?

🔹 Example #4
📈 Probability: 0.949
📝 скорее не отзыв,а вопрос - Раздали готовые бланки для принудительного вступления в профсоюз.Кому и куда можно пожаловаться ,если я не желаю никуда вступать,платить взносы не понять куда и для чего.

🔹 Example #5
📈 Probability: 0.942
📝 А в правничому коледжі на заочній формі навчаня втрачається рік чи ні?? там потрібно на заочному віділеню вчитись 3. чи 3.споловиною роки??? і якщо три споловиною то рік втрачається?

====================================================================================================
🏷️ Education_Quality
====================================================================================================

🔹 Example #1
📈 Probability: 0.978
📝 Нажаль більшість викладачів лише теоретики і не мають жодних практичних навичок та досвіду роботи на виробництві. Матеріально-технічна база застаріла. Краще поступати у ВУЗ в іншому регіоні.

🔹 Example #2
📈 Probability: 0.974
📝 Скажем так: преподаватели - это экономисты, географы, которых не взяли работать в другие вузы, где специальность "туризм" была открыта с 90-х годов. Или вообще не знающие специальность люди - культурологи и т.п.

🔹 Example #3
📈 Probability: 0.973
📝 Прикладна лінгвістика - це найгірший мій вибір. Ниікому не раджу поступати сюди.З  англійської мови знання тільки погіршились. Забивають голову всякими непотрібними теоритичними технічними дисциплінами, які ніяк не пригодились.З інформаційних технологій - вчитимите Turbo Pascal і на тому й все закінчиться.Хто хоче дійсно стати Філологом , Викладачем або Перекладачем - тут Ви ним не станете.

🔹 Example #4
📈 Probability: 0.963
📝 Хочу сказать что уровень знаний на 0. Преподаватели не знают предмет и не учат, а потом орут почему ничего не знаешь. Хамы и злые. Поступайте лучше в доугой универ.

🔹 Example #5
📈 Probability: 0.956
📝 Якість освіти. Це неправда. За 4 роки лише 2 викладачі були дійсно цікаві й професійні. Інші — це люди, що живуть у своєму світі, сидять на бронюванні і яких ніколи не звільнять. Мої друзі з інформатики вивчали застарілі мови програмування 90-х і 2000-х років, які ніде не використовуються. Викладачів можна поділити на кілька категорій: професіонали (меншість), шизи, що не вміють користуватися компом, та виносять мозок, щоб закрити хоча б на 60, особливо на непрофільних предметах. Були викладачі, що змушували переповідати сказане ними в лекціях ледь не слово в слово (вітання Чумаченку). Є й професори по 70-80 років, які сидять як паразити і несуть повну шизу, але їх не звільнять. На гуманітарних предметах — черги на семінари по 10-15 людей. Викладачі з КНУ це взагалі окремий підвид. Одна змушувала писати конспекти за оцінку, інший змушував на семінарах цитувати лише першоджерела і власний аналіз /трактування взагалі не приймався за відповідь.

**2. Random prediction examples**

In [70]:
# ------------------------------------------------------------
# Random Prediction Examples (all probabilities)
# ------------------------------------------------------------

random_examples = negative_unlabeled.sample(
    n=5,
    random_state=42
)

for idx, row in random_examples.iterrows():

    print("\n" + "="*120)
    print(f"🔹 Review ID: {idx}")
    print(f"📝 {row['Review Text']}")

    print("\n📊 Probabilities:")

    for i, label in enumerate(label_cols):

        prob = row[f"{label}_prob"]

        mark = "✅" if prob >= thresholds[i] else "❌"

        print(
            f"{mark} {label:<30} "
            f"{prob:.3f}"
        )

    print("="*120)

========================================================================================================================
🔹 Review ID: 1467
📝 Історичний факультет, дуже хороші викладачі, ніяких претензій до них немає, пояснюють на найвищому рівні. А до деканату іст факу є претензії та скарги. Це нормально, що у «найкращому» університеті працюють такі хамки? Жодної нормальної відповіді на запитання студента, тільки грубість. Не розуміють з першого разу та навіть не слухають, можуть собі дозволити обізвати студента. Це просто неможливо, поміняйте персонал, таке відчуття наче вони там прийшли похамили, поїли і пішли додому. Дуже щаслива, що відрахувалася та більше ніколи не вступлю у цей жахливий університет. Із приємного у цьому університеті тільки одногрупники та друзі, яких можна зустріти. Більше плюсів у цього універу немає. Якщо при вступі вам цілували руки і ноги то під час навчання об вас витиратимуть ноги тітоньки із деканату. -10000 із 10, краще б пішла в НУБІП!!

📊 Probabilities:
✅ Attitude_Towards_Students      0.859
❌ Campus_conditions              0.162
❌ Corruption                     0.331
❌ Academic_Process_Management    0.439
❌ Education_Quality              0.492
========================================================================================================================

========================================================================================================================
🔹 Review ID: 1871
📝 На початку року обіцяли нам лояльність до студентів і те що сесію здадуть усі , проте як тільки прийшла сесія викладачі просто валили. Навіть в період війни ніяка совість у цих викладачів не проснулась!

📊 Probabilities:
✅ Attitude_Towards_Students      0.829
❌ Campus_conditions              0.216
❌ Corruption                     0.264
✅ Academic_Process_Management    0.638
❌ Education_Quality              0.190
========================================================================================================================

========================================================================================================================
🔹 Review ID: 1019
📝 Закончила Мехмат в 2016 году. Работу по специальности нашла только через полтора года, и то с большими трудностями. Диплом Мехмата не котируется нигде. Хотя первое, что говорят при поступлении, что наш диплом это пропуск в успешную жизнь. Насчёт взяток правда, что большенству преподов лучше даже не предлагать.. будет только хуже, но это не касается руководства с ним решаешься любой вопрос за взятку и при том ооочень не малую, иногда отправляет на эконом к своей жене, что бы $€ отдавали ей. В общем беспросветная мгла, а не факультет.

📊 Probabilities:
❌ Attitude_Towards_Students      0.360
❌ Campus_conditions              0.111
✅ Corruption                     0.726
❌ Academic_Process_Management    0.424
✅ Education_Quality              0.527
========================================================================================================================

========================================================================================================================
🔹 Review ID: 1902
📝 Провчилась в ЛНУ місяць і вже в шоці. Економічний факультет все дуже стареньке, сам факультет повністю в тріщинах, ремонти погані. Школа в якій я вчилась була з кращими ремонтами і меблями, тому не розумію чому університет так виглядає.
Тепер перевели на дистанційне навчання, побачимо, що буде дальше.

📊 Probabilities:
❌ Attitude_Towards_Students      0.181
✅ Campus_conditions              0.805
❌ Corruption                     0.301
✅ Academic_Process_Management    0.715
✅ Education_Quality              0.588
========================================================================================================================

========================================================================================================================
🔹 Review ID: 2224
📝 Потерял время, получил кучу абсолютно бесполезных "знаний".
Все что в жизни пригодилось по специальности пришлось учить самому еще до универа. Мог бы сэкономить себе все эти годы, добился бы больших успехов.
Американские курсы на Coursera и  Udemy несравнимо более полезны, чем сборище непонятно кого в КПИ (и наверное в любом другом ВУЗе страны).

До этого учился в еще более убогом ВУЗе.
Как можно было два раза так лохануться, позор мне.

📊 Probabilities:
❌ Attitude_Towards_Students      0.239
❌ Campus_conditions              0.072
❌ Corruption                     0.434
❌ Academic_Process_Management    0.432
✅ Education_Quality              0.836
========================================================================================================================

**3. Borderline Prediction Examples**

The following examples correspond to reviews whose predicted probabilities are closest to the decision threshold. These cases illustrate situations where the classifier is uncertain and where manual review may be beneficial.

In [71]:
for i, label in enumerate(label_cols):

    threshold = thresholds[i]

    lower = threshold - 0.03
    upper = threshold + 0.03

    borderline = negative_unlabeled[
        negative_unlabeled[f"{label}_prob"].between(
            lower,
            upper
        )
    ]

    print(
        f"\n🏷️ {label}: "
        f"{len(borderline)} borderline reviews"
    )

🏷️ Attitude_Towards_Students: 133 borderline reviews

🏷️ Campus_conditions: 76 borderline reviews

🏷️ Corruption: 90 borderline reviews

🏷️ Academic_Process_Management: 141 borderline reviews

🏷️ Education_Quality: 136 borderline reviews

In [72]:
class_name = "Corruption"

threshold = thresholds[label_cols.index(class_name)]

tmp = negative_unlabeled.copy()

tmp["distance"] = abs(
    tmp[f"{class_name}_prob"] - threshold
)

closest = tmp.sort_values(
    "distance"
).head(10)

for _, row in closest.iterrows():

    print("\n" + "="*120)

    print(
        f"📈 Probability: "
        f"{row[f'{class_name}_prob']:.3f}"
    )

    print(
        f"🎯 Threshold: "
        f"{threshold:.2f}"
    )

    print(f"📝 {row['Review Text']}")

========================================================================================================================
📈 Probability: 0.501
🎯 Threshold: 0.50
📝 Не советую поступать на любой факультет этого  университета, ректор на уступки никто не идёт , даже когда он нарушил закон и признает это. Спокойно могут отчислить в любой момент , а самое интересное без  причины . Общежития ужасные , тараканы повсюду , антисанитария полная .  Если вы дорожите своим временем , прислушайтесь к моему совету !!!!

========================================================================================================================
📈 Probability: 0.499
🎯 Threshold: 0.50
📝 Ужасный университет, никакого образования нет. Гребут только деньги и все. Никому не рекомендую туда поступать

========================================================================================================================
📈 Probability: 0.499
🎯 Threshold: 0.50
📝 Не тратьте свои нервы и деньги!

========================================================================================================================
📈 Probability: 0.502
🎯 Threshold: 0.50
📝 Що я можу сказати про УКУ – тут класна трапезна, велика бібліотека і гарний інтер’єр. Але це напевно всі плюси УКУ. За такі гроші я очікувала більше, коли вступала сюди. Викладачі викладають свої предмети посередньо, іноді взагалі халатно ставляться до своїх обов`язків. Дискримінація студентів присутня, хоча й не у відкритому вигляді. Рівень навчання подекуди навіть нижчий, ніж в державних університетах. Стосовно отримання стипендії на навчання, то тут все дуже суперечливо... На старших курсах факультетська стипендія вже не діє. Є лише мотиваційна, яку дають «вибраним» студентам. Є ще соціальна, але на неї можете навіть не сподіватися, якщо ви не сирота чи не з малозабезпеченої сім’ї. На сесіях доволі часто занижують бали, що взагалі відбиває бажання навчатися і до чогось прагнути. Тому, якщо ваша сім’я не настільки заможна, щоб оплачувати 80 тисяч в рік на навчання, то сміливо вступайте в державний ВНЗ і отримаєте нічим не гірші знання. А головне – збережете гроші і здоров‘я.

========================================================================================================================
📈 Probability: 0.502
🎯 Threshold: 0.50
📝 ПОЛНОСТЬЮ СОГЛАСНА: хну сейчас уже не тот что был,  особенно иняз, не поступайте на иняз, ничего дельного здесь не получите! а на других фак., говорят , что ситуация получше ...........

========================================================================================================================
📈 Probability: 0.502
🎯 Threshold: 0.50
📝 Очаг преподавания экономических псевдонаук.  Среди студентов преобладают  недалекие недотепы и дремучие провинциалы, мечтающие разбогатеть. Здесь ничему не научат, да и некому учить. Зато требовать знаний тоже никто не будет. 4 года пройдут в грезах о блестящей карьере  и в расслабленном состоянии.  Вам будут давать примитивные задания, ставить балы, хвалить и рисовать высокие рейтинги. Требуется только своевременная оплата учебы.  Большинство студентов на парах играется с мобильным телефоном или вообще на них не ходит. На экзаменах и контрольных поголовное списывание. Получив диплом, можно продолжить обучение в университете ( если есть деньги) либо сразу  пополнить  ряды продавцов и безработных.

========================================================================================================================
📈 Probability: 0.497
🎯 Threshold: 0.50
📝 КНЕУ - Універ (ЖИР) все в ньому круто. Але є і підводні камені, про які ви дізнаєтеся на власному досвіді і болісно б'ють поборах по своїй кишені. Преподу прикольні адекватні все реально професіонали своєї справи. Але при захисті диплома вам можуть на всю аудиторію сказати що ви не наш студент. Всі хто пише дипломні роботи плюються Наргосп та це ж КОЛХОЗ. Є й заслони казочки казкові на всю голову, якийсь Діма Олександр Олексійович. У чому суть питання не в якому разі не пишіть і не захищайте Диплом. роботу у нього. Не коли не приходить на консультації під час постійно переносить час (причому спеціально). У рецензії пише 100% негатив. Тієї є такі викладачі нас вчать. Круто. -Діма Олександр Олексійович.https://fm.kneu.edu.ua/ua/depts3/kkdl/vikladachi_kkdl/Dima.O.O/

========================================================================================================================
📈 Probability: 0.503
🎯 Threshold: 0.50
📝 Зря выброшенные деньги! Если есть альтернатива этому "ВУЗу", то смело выбирайте любой другой!!! Как можно чему- то научить студентов, если начиная от методистов и заканчивая профессорами, ВСЕМ ПОФИГ НА ВАС И ВАШИ ЗНАНИЯ !!! что- то узнать тут у Вас врядли выйдет, как и добиться того что бы чему то учили тоже.

========================================================================================================================
📈 Probability: 0.503
🎯 Threshold: 0.50
📝 Закінчила кафедру МП  (магістр 2017) навчалась на 5рки  сама, окрім фізри - як там не стрибай і не бігай - сертифікат в космо на тисячу треба заплатити, щоб була 4ка. Хочу сказати, що навчання саме по публічному праву в мене було хорошим, але наскільки відомо, після зміни керівництва кафедри там робиться зараз жах. По національному праву - потрібно все вивчати самому, самонавчання, саморозвиток. Власне, це і вплинуло на те, що більшість моєї групи не змогли знайти роботу, адже посади юристів-міжнародників не численні, а в національному праві треба розбиратися. Крім того, коли в резюме бачать освіту НАУ, часто відмовляють, більшість хороших роботодавців хочуть або Шевченка, або Я. Мудрого, УКУ, Львів. Читаю відгуки і розумію, що з років мого навчання нічого не змінилось - хіба що погіршилось.гарячої води, до речі, кожен рік немає з Великдня і по початок сезону опалювання. бачу дуже багато хороших відгуків -  я звісно рада, що кому сподобалось, але так академічно написано, що сумніваюсь

========================================================================================================================
📈 Probability: 0.497
🎯 Threshold: 0.50
📝 На міжнародні відносини в магістратуру навіть і не рипайтесь. Марна справа, тільки згаєте час. поступають свої або при грошах. на вступних поставлять 65 балів і не пройдете навіть на контракт.особливо якщо ви з іншого міста або вузу як я.